### ISSUE TITLE
111

### ISSUE THREAD

**Issue by lu0de** [lu0de/Digital_ic_final#1]

**Comment by Takusei-51775** [comment]
前年考试题
https://elearning.shanghaitech.edu.cn:8443/bbcswebdav/pid-66260-dt-content-rid-5709914_1/courses/EE213-100139-2768-2021-20221/Exam-final-F21.pdf
无答案

**Comment by lu0de** [comment]
无答案言diao

**Comment by Takusei-51775** [comment]
确实

对了，你有能打开的伯克利作业答案吗？我记得学期中打开过他们网站，现在无法访问了

**Comment by Takusei-51775** [comment]
数字集成电路快速复习指南 https://ys.mihoyo.com

**Comment by Takusei-51775** [comment]
test
